#!/bin/bash

. /etc/init.d/functions

start() {
   nohup boundary server -config=/boundary-worker/config/config.hcl > /boundary-worker/logs/log.out 2>&1 &
}


stop() {
   killproc boundary
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 