#!/bin/bash

. /etc/init.d/functions

start() {
   nohup vault server -config=/vault/config/config.hcl > /vault/logs/log.out 2>&1 &
}

stop() {
   killproc vault
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 